# Logistic Regression

### Aaron Gonzales
### CS529, Machine Learning
### Project 3
### Instructor: Trilce Estrada

### rubric
- Implement gradient descent (Code – 15 pts) x
- Implement multinomial logistic regression (Code – 15 pts) x
- Provide comments and README (Code & Documentation – 5 pts)

- Use FFT components for classification (Code - 5 pts) x 

- Use 10-fold cross validation for training and testing (Code - 5 pts) 
- Report accuracy with the confusion matrix (Report – 5 pts) x 

- Describe results and provide an explanation for bias (Report - 5 pts)

- Define a rank for FFT components and use 200 for classification (Code - 5 pts) 
- Use 10-fold cross validation for training and testing (Code - 5 pts)

- Report accuracy with the confusion matrix (Report - 5 pts)

- Describe results and provide an explanation for bias (Report - 5 pts)

- Use MFCC components for classification (Code - 5 pts)

- Use 10-fold cross validation for training and testing (Code - 5 pts) 
- Report accuracy with the confusion matrix (Report - 5 pts)

- Describe results and provide an explanation for bias (Report - 5 pts)

- Describe how could you improve further this classification task (Report - 5 pts) 

- Total 100 pts (This homework accounts for 10 points of your final grade)


## Overview of the project

We built a thing that does stuff.

blah blah blah. 

This is an ipython notebook; code can be executed direclty from here. 

explain how to run the program.


In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import sklearn.metrics  as metrics
import utils as utils
from LogisticRegressionClassifier import LogisticRegressionClassifier

I had previously extracted the ffts and mcfts from the data; all of them live in the /data/ folder of this package. As such, loading them in is easy. Methods to extract them are in the `fft.py` and `mfcc.py` files; both were ran from an IPython environment. The FFT data was scaled to {0, 1} and the mfcs were scaled via z-score. the data is the variables `(fft, mfcs)`, the labels are hopefully labeled clearly enough, and the dictionary is just a mapping of label ID to actual english word.

In [2]:
fft_dict, fft_labels, ffts = utils.read_features(feature='fft')
mfc_dict, mfc_labels, mfcs = utils.read_features(feature='mfc')

The classifer is implemented as a class and holds its metrics and data information internally after calls to its methods. It is initialized with the data as given:

In [3]:
lrc_fft = LogisticRegressionClassifier(ffts, fft_labels, fft_dict)
lrc_mfc = LogisticRegressionClassifier(mfcs, mfc_labels, mfc_dict)

## FFT components

Now that we have our data loaded, we can go ahead and fit the logistic regression model to it. Internally it is performing 10-fold cross validation with shuffling via Sklearn's `cross_validated` module. 

### Gradient Descent
I went with the vectorized version of gradient descent discussed in Piazza. My learning rate was adaptive to the custom 'error' rate defined as the max value from the dot product between the  

$$\Delta

In [5]:
lrc_fft.cross_validate()

Training cross validation round 0
----------------------------------
Step 0: Error: -1.000000 updating learning rate: 0.001000
Final Step 1000: Error: 0.120369 
 Learn rate: 0.001000
classification report 
----------------------------------
             precision    recall  f1-score   support

      blues       0.30      0.30      0.30        10
      disco       0.50      0.38      0.43        13
       rock       0.38      0.27      0.32        11
     reggae       0.11      0.10      0.11        10
       jazz       0.22      0.29      0.25         7
  classical       0.47      0.78      0.58         9
     hiphop       0.18      0.25      0.21         8
        pop       0.33      0.43      0.38         7
      metal       0.82      0.75      0.78        12
    country       0.38      0.23      0.29        13

avg / total       0.39      0.38      0.38       100

Confusion matrix
----------------------------------
[[3 0 1 3 2 0 0 0 1 0]
 [0 5 2 0 2 0 2 2 0 0]
 [1 1 3 2 0 0 1 0 1 2]

These are not the best scores i've ever seen.

Selecting only the features that have moderate variance gives us a set of 200 to test.

In [7]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(0.01150)
a = sel.fit_transform(ffts)
a.shape
lr = LogisticRegressionClassifier(a, fft_labels, fft_dict)
lr.cross_validate()

Training cross validation round 0
----------------------------------
Step 0: Error: -1.000000 updating learning rate: 0.001000
Final Step 1000: Error: 0.209789 
 Learn rate: 0.001000
classification report 
----------------------------------
             precision    recall  f1-score   support

      blues       0.23      0.43      0.30         7
      disco       0.20      0.15      0.17        13
       rock       0.30      0.33      0.32         9
     reggae       0.09      0.09      0.09        11
       jazz       0.14      0.08      0.11        12
  classical       1.00      0.25      0.40         8
     hiphop       0.12      0.10      0.11        10
        pop       0.60      0.43      0.50        14
      metal       0.22      0.67      0.33         6
    country       0.18      0.20      0.19        10

avg / total       0.30      0.25      0.25       100

Confusion matrix
----------------------------------
[[3 0 0 2 1 0 0 0 0 1]
 [1 2 5 0 0 0 1 0 3 1]
 [1 0 3 0 0 0 2 0 2 1]

Those scores went down, so I presume that I did something wrong or that ther is incredible bias or multicoliniarty in this model. I'll try PCA and see how that goes.

In [8]:
from sklearn.decomposition import PCA

In [9]:
p = PCA(n_components=200)

In [103]:
pcad = p.fit_transform(ffts)

(1000, 200)