In [14]:
import numpy as np
import itertools

In [94]:
%load_ext autoreload
%autoreload 1

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [95]:
%aimport utils
%aimport classify

In [325]:
classes, class_labels, ffts = utils.read_features()

In [326]:
ffts = np.absolute(ffts)
ffts = np.insert(ffts, 0, 1, axis=1)
ffts.shape
ffts = ffts /np.max(ffts)

(1000, 1001)

In [5]:
classes

{'blues': 5,
 'classical': 3,
 'country': 6,
 'disco': 4,
 'hiphop': 1,
 'jazz': 9,
 'metal': 0,
 'pop': 8,
 'reggae': 2,
 'rock': 7}

In [6]:
len(class_labels)


1000

True

In [7]:
## estimate priors?

class_priors = np.zeros(shape=len(classes))

In [8]:
for k, v in classes.items():
    view = class_labels[class_labels == v]
    class_priors[v] = view.size/class_labels.size

In [9]:
class_priors

array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1])

In [10]:
phat = np.zeros((len(classes), ffts.shape[1]))
phat.shape

(10, 1000)

In [33]:
hash('a')


1736683925360687992

In [34]:
hash('b')

-1815693260366656874

In [35]:
hash(1)

1

In [36]:
hash(1.1)

230584300921369601

'9567 + 1085 == 10652'

In [11]:
name = 'carly'
chars = set(name)
chars

{'a', 'c', 'l', 'r', 'y'}

In [12]:
ords = tuple(ord(c) for c in set(name))

In [15]:
list(itertools.combinations(ords, 3))

[(114, 108, 99),
 (114, 108, 97),
 (114, 108, 121),
 (114, 99, 97),
 (114, 99, 121),
 (114, 97, 121),
 (108, 99, 97),
 (108, 99, 121),
 (108, 97, 121),
 (99, 97, 121)]

In [100]:
## I need a big delta matrix for $\delta(y^l = y_j)$

Delta = classify.make_Delta(class_labels, len(classes))



P(Y|W,X)∼exp(WXT), a t×m matrix of probability values. To follow the format of equations (27) and (28) in the text, fill the last row with all 1's, and then normalize each column to sum to one by dividing the each value in the column by the sum of the column.

(10, 1000)

In [263]:
def probs(Weights, X):
    P = np.log(np.exp(np.dot(Weights, X.T)))
    P[P.shape[0]-1] = 1
    colsum = np.sum(P, axis=0)
    P = P/colsum
    return P

In [330]:
W.shape

(10, 1000)

-0j

Wt+1=Wt+η((Δ−P(Y|W,X))X−λWt)

TypeError: 'float' object is not callable

In [421]:
W = np.zeros(shape=(len(classes), ffts.shape[1]), dtype='float64')
W.shape



(10, 1001)

In [422]:
W = classify.grad_decent(ffts, W, Delta, _lambda=5, eta = 0.000001, rounds = 10000, debug=False)

Error: 5.167005 
 Learn rate: 0.000001


In [349]:
_delta = 0
d = 0
f = 0


In [399]:
for i in range(1000):
    _delta = Delta - classify.logistic(ffts, W)
    d = np.dot(_delta, ffts)
    f = d - (10 * W)
    W = W + 0.0001*f

Error: 5.068642 
 Learn rate: 0.000000


In [413]:
W

array([[ -7.18359674e-08,  -2.48786090e-03,  -5.09591162e-03, ...,
          6.00080512e-02,   7.40970080e-03,  -5.09591162e-03],
       [ -6.53930026e-08,   3.83073598e-02,   6.49824528e-02, ...,
          2.46530591e-01,   3.17559390e-01,   6.49824528e-02],
       [ -6.42844965e-08,   1.62803769e-02,   5.67110844e-03, ...,
          2.58519536e-01,  -2.46483568e-02,   5.67110844e-03],
       ..., 
       [ -6.45306845e-08,  -2.72149668e-02,  -3.84394542e-02, ...,
         -1.62414021e-01,  -9.61795951e-02,  -3.84394542e-02],
       [ -6.59576361e-08,   4.34014344e-02,   1.02112944e-01, ...,
          1.49804130e-01,   2.68313453e-01,   1.02112944e-01],
       [  5.83490754e-07,   7.19360519e-02,   5.53531423e-02, ...,
          1.45461029e-01,   1.10198410e-01,   5.53531423e-02]])

In [298]:
P[P.shape[0]-1] = 1


In [299]:
colsum = np.sum(P, axis=0)


In [300]:
P = P/colsum
P


array([[ 0.1323223 ,  0.1323223 ,  0.1323223 , ...,  0.1323223 ,
         0.1323223 ,  0.1323223 ],
       [ 0.1323223 ,  0.1323223 ,  0.1323223 , ...,  0.1323223 ,
         0.1323223 ,  0.1323223 ],
       [ 0.1323223 ,  0.1323223 ,  0.1323223 , ...,  0.1323223 ,
         0.1323223 ,  0.1323223 ],
       ..., 
       [ 0.1323223 ,  0.1323223 ,  0.1323223 , ...,  0.1323223 ,
         0.1323223 ,  0.1323223 ],
       [ 0.1323223 ,  0.1323223 ,  0.1323223 , ...,  0.1323223 ,
         0.1323223 ,  0.1323223 ],
       [-0.19090073, -0.19090073, -0.19090073, ..., -0.19090073,
        -0.19090073, -0.19090073]])

In [301]:
_delta = Delta - P
_delta


array([[-0.1323223 , -0.1323223 , -0.1323223 , ..., -0.1323223 ,
        -0.1323223 , -0.1323223 ],
       [ 0.8676777 , -0.1323223 , -0.1323223 , ..., -0.1323223 ,
        -0.1323223 , -0.1323223 ],
       [-0.1323223 ,  0.8676777 , -0.1323223 , ...,  0.8676777 ,
        -0.1323223 , -0.1323223 ],
       ..., 
       [-0.1323223 , -0.1323223 , -0.1323223 , ..., -0.1323223 ,
        -0.1323223 , -0.1323223 ],
       [-0.1323223 , -0.1323223 , -0.1323223 , ..., -0.1323223 ,
        -0.1323223 , -0.1323223 ],
       [ 0.19090073,  0.19090073,  0.19090073, ...,  0.19090073,
         0.19090073,  0.19090073]])

In [302]:
d = np.dot(_delta, ffts)
d


array([[ -3.72934390e+06,  -4.76042546e+06,  -8.91721495e+06, ...,
         -4.97800795e+06,  -8.91721495e+06,  -4.76042546e+06],
       [  2.41091910e+06,   5.86999657e+06,   3.84811439e+07, ...,
          2.31485526e+07,   3.84811439e+07,   5.86999657e+06],
       [ -1.01508590e+06,  -3.31481745e+06,  -1.44093802e+07, ...,
          2.48854758e+07,  -1.44093802e+07,  -3.31481745e+06],
       ..., 
       [ -7.72148090e+06,  -1.01150501e+07,  -2.54305297e+07, ...,
         -4.00491089e+07,  -2.54305297e+07,  -1.01150501e+07],
       [  3.21066910e+06,   1.16162364e+07,   3.09221033e+07, ...,
          8.27911306e+06,   3.09221033e+07,   1.16162364e+07],
       [  4.27302101e+07,   4.61112677e+07,   1.12100627e+08, ...,
          1.57034808e+08,   1.12100627e+08,   4.61112677e+07]])

In [303]:
f = d - (1000 * W)
f

array([[ -3.72934390e+06,  -4.76042546e+06,  -8.91721495e+06, ...,
         -4.97800795e+06,  -8.91721495e+06,  -4.76042546e+06],
       [  2.41091910e+06,   5.86999657e+06,   3.84811439e+07, ...,
          2.31485526e+07,   3.84811439e+07,   5.86999657e+06],
       [ -1.01508590e+06,  -3.31481745e+06,  -1.44093802e+07, ...,
          2.48854758e+07,  -1.44093802e+07,  -3.31481745e+06],
       ..., 
       [ -7.72148090e+06,  -1.01150501e+07,  -2.54305297e+07, ...,
         -4.00491089e+07,  -2.54305297e+07,  -1.01150501e+07],
       [  3.21066910e+06,   1.16162364e+07,   3.09221033e+07, ...,
          8.27911306e+06,   3.09221033e+07,   1.16162364e+07],
       [  4.27302101e+07,   4.61112677e+07,   1.12100627e+08, ...,
          1.57034808e+08,   1.12100627e+08,   4.61112677e+07]])

In [304]:
W = W + (0.00001 * f)

In [305]:
W

array([[  -37.29343901,   -47.60425455,   -89.17214948, ...,
          -49.78007953,   -89.17214948,   -47.60425455],
       [   24.10919099,    58.69996568,   384.81143939, ...,
          231.48552632,   384.81143939,    58.69996568],
       [  -10.15085901,   -33.14817455,  -144.09380204, ...,
          248.85475764,  -144.09380204,   -33.14817455],
       ..., 
       [  -77.21480901,  -101.15050099,  -254.30529734, ...,
         -400.49108901,  -254.30529734,  -101.15050099],
       [   32.10669099,   116.16236433,   309.22103315, ...,
           82.79113063,   309.22103315,   116.16236433],
       [  427.30210108,   461.11267665,  1121.00627366, ...,
         1570.34807618,  1121.00627366,   461.11267665]])