In [1]:
import utils
import numpy as np

In [2]:
classes, class_labels, ffts = utils.read_features()

In [3]:
classes

{'blues': 3,
 'classical': 4,
 'country': 1,
 'disco': 9,
 'hiphop': 0,
 'jazz': 8,
 'metal': 7,
 'pop': 5,
 'reggae': 2,
 'rock': 6}

In [5]:
len(class_labels)


1000

True

In [25]:
## estimate priors?

class_priors = np.zeros(shape=len(classes))

In [26]:
for k, v in classes.items():
    view = class_labels[class_labels == v]
    class_priors[v] = view.size/class_labels.size

In [27]:
class_priors

array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1])

In [28]:
phat = np.zeros((len(classes), ffts.shape[1]))
phat.shape

(10, 1000)

In [33]:
hash('a')


1736683925360687992

In [34]:
hash('b')

-1815693260366656874

In [35]:
hash(1)

1

In [36]:
hash(1.1)

230584300921369601

In [37]:


import re
import itertools

def solve(puzzle):
    words = re.findall('[A-Z]+', puzzle.upper())
    unique_characters = set(''.join(words))
    assert len(unique_characters) <= 10, 'Too many letters'
    first_letters = {word[0] for word in words}
    n = len(first_letters)
    sorted_characters = ''.join(first_letters) + \
        ''.join(unique_characters - first_letters)
    characters = tuple(ord(c) for c in sorted_characters)
    digits = tuple(ord(c) for c in '0123456789')
    zero = digits[0]
    for guess in itertools.permutations(digits, len(characters)):
        if zero not in guess[:n]:
            equation = puzzle.translate(dict(zip(characters, guess)))
            if eval(equation):
                return equation

In [40]:
sol = solve('SEND + MORE == MONEY')
sol

'9567 + 1085 == 10652'

In [52]:
name = 'carly'
chars = set(name)
chars

{'a', 'c', 'l', 'r', 'y'}

In [55]:
ords = tuple(ord(c) for c in set(name))

In [63]:
list(itertools.combinations(ords, 3))

[(97, 121, 108),
 (97, 121, 114),
 (97, 121, 99),
 (97, 108, 114),
 (97, 108, 99),
 (97, 114, 99),
 (121, 108, 114),
 (121, 108, 99),
 (121, 114, 99),
 (108, 114, 99)]

In [58]:
hash((1,2))

3713081631934410656

In [65]:
a = np.array([0,1,1,2,3,4,10,0])
(1 / ( 1 + np.exp(a)))

array([  5.00000000e-01,   2.68941421e-01,   2.68941421e-01,
         1.19202922e-01,   4.74258732e-02,   1.79862100e-02,
         4.53978687e-05,   5.00000000e-01])

In [87]:

W = np.zeros(shape=(len(classes), ffts.shape[1])) + 0.5
W.shape
W

array([[ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5],
       ..., 
       [ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5]])

In [94]:
np.dot(W, ffts)

array([[-10220074.50000000      +0.j        ,
           413067.69159501-1251276.83954865j,
          9297048.50451787-6392168.18942727j, ...,
         -8651752.59336352+9399981.48754334j,
          9297048.50451789+6392168.18942722j,
           413067.69159500+1251276.83954865j],
       [-10220074.50000000      +0.j        ,
           413067.69159501-1251276.83954865j,
          9297048.50451787-6392168.18942727j, ...,
         -8651752.59336352+9399981.48754334j,
          9297048.50451789+6392168.18942722j,
           413067.69159500+1251276.83954865j],
       [-10220074.50000000      +0.j        ,
           413067.69159501-1251276.83954865j,
          9297048.50451787-6392168.18942727j, ...,
         -8651752.59336352+9399981.48754334j,
          9297048.50451789+6392168.18942722j,
           413067.69159500+1251276.83954865j],
       ..., 
       [-10220074.50000000      +0.j        ,
           413067.69159501-1251276.83954865j,
          9297048.50451787-6392168.18942727j, ...